import type { Metadata } from "next";
import "./globals.css";
import { Nav } from "./ui/nav";
import { montserrat } from "./ui/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased bg-cover bg-center`}>
        <div className="mx-auto w-[1280px]  min-h-screen">
          <Nav />
          {children}
        </div>
      </body>
    </html>
  );
}
